# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'valheim-server'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 4096

[experimental]
  auto_rollback = true

[build]

[env]
  VALHEIM_SERVER_FLAGS = '-port 3456 -name World -world world -password foobar'

[http_service]
  internal_port = 2456
  force_https = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = 'valheim_data'
  destination = '/home/valheim'
  initial_size = '10'

[[services]]
  protocol = 'tcp'
  internal_port = 2456

  [[services.ports]]
    port = 2456

[[services]]
  protocol = 'tcp'
  internal_port = 2457

  [[services.ports]]
    port = 2457

[[services]]
  protocol = 'udp'
  internal_port = 2456

  [[services.ports]]
    port = 2456

[[services]]
  protocol = 'udp'
  internal_port = 2457

  [[services.ports]]
    port = 2457

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
